# Generated by Django 5.0.6 on 2024-06-12 07:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("interne_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="employee_profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_email", models.EmailField(max_length=254, unique=True)),
                ("full_name", models.CharField(max_length=20)),
                ("user_phone", models.CharField(max_length=10, unique=True)),
            ],
        ),
    ]
