# Generated by Django 5.0.6 on 2024-06-12 09:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("interne_app", "0002_employee_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee_profile",
            name="father_name",
            field=models.CharField(default="not known", max_length=20),
            preserve_default=False,
        ),
    ]
