# Generated by Django 5.0.6 on 2024-06-12 09:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("interne_app", "0003_employee_profile_father_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee_profile",
            name="gender",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                default="M",
                max_length=1,
            ),
        ),
    ]
