# Generated by Django 5.0.6 on 2024-06-17 07:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("interne_app", "0004_employee_profile_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee_login",
            name="roleid",
            field=models.IntegerField(
                choices=[(1, "Admin"), (2, "Employee")], default=2, max_length=1
            ),
        ),
    ]
