# Generated by Django 5.0.6 on 2024-06-17 11:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("interne_app", "0005_employee_login_roleid"),
    ]

    operations = [
        migrations.CreateModel(
            name="admin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("admin_email", models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
