# Generated by Django 5.0.6 on 2024-06-17 11:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("interne_app", "0006_admin"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="admin",
            new_name="admin_profile",
        ),
    ]
