# Generated by Django 5.0.6 on 2024-06-17 12:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("interne_app", "0007_rename_admin_admin_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="admin_profile",
            name="admin_name",
            field=models.CharField(default="unknown", max_length=20),
            preserve_default=False,
        ),
    ]
