# Generated by Django 5.0.6 on 2024-06-20 03:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("interne_app", "0008_admin_profile_admin_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="employee_profile",
            old_name="full_name",
            new_name="first_name",
        ),
        migrations.AddField(
            model_name="employee_profile",
            name="last_name",
            field=models.CharField(default="unknown", max_length=20),
            preserve_default=False,
        ),
    ]
