# Generated by Django 5.0.6 on 2024-06-20 09:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("interne_app", "0009_rename_full_name_employee_profile_first_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Gender",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Others")],
                        default="M",
                        max_length=1,
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="employee_profile",
            name="gender",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female"), ("O", "Others")],
                default="M",
                max_length=1,
            ),
        ),
    ]
