# Generated by Django 5.0.6 on 2024-06-22 09:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("interne_app", "0010_gender_alter_employee_profile_gender"),
    ]

    operations = [
        migrations.DeleteModel(
            name="admin_profile",
        ),
        migrations.DeleteModel(
            name="employee_login",
        ),
        migrations.DeleteModel(
            name="employee_profile",
        ),
        migrations.DeleteModel(
            name="Gender",
        ),
    ]
