# Generated by Django 5.0.6 on 2024-06-22 09:17

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("interne_app", "0011_delete_admin_profile_delete_employee_login_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="admin_profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("admin_email", models.EmailField(max_length=254, unique=True)),
                ("admin_name", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="employee_login",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(max_length=20, unique=True)),
                ("password", models.CharField(max_length=10)),
                (
                    "roleid",
                    models.IntegerField(
                        choices=[(1, "Admin"), (2, "Employee")], default=2, max_length=1
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="employee_profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_email", models.EmailField(max_length=254, unique=True)),
                ("first_name", models.CharField(max_length=20)),
                ("last_name", models.CharField(max_length=20)),
                ("user_phone", models.CharField(max_length=10, unique=True)),
                ("father_name", models.CharField(max_length=20)),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Others")],
                        default="M",
                        max_length=1,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Gender",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Others")],
                        default="M",
                        max_length=1,
                    ),
                ),
            ],
        ),
    ]
